### ISSUE TITLE
Repo subtitle link refers to 404 page

### ISSUE THREAD

**Issue by Alexandre-Nourissier** [vfabing/sample-selenium-dotnet#1]
is 
[http://www.vivienfabing.com/automated-testing/2019/02/06/how-to-keep-your-ui-test-maintainable-over-time-welcome-page-object-pattern.html ](http://www.vivienfabing.com/automated-testing/2019/02/06/how-to-keep-your-ui-test-maintainable-over-time-welcome-page-object-pattern.html )
should be 
[https://www.vivienfabing.com/automated-testing/2019/02/14/how-to-keep-your-ui-test-maintainable-over-time-welcome-page-object-pattern.html](https://www.vivienfabing.com/automated-testing/2019/02/14/how-to-keep-your-ui-test-maintainable-over-time-welcome-page-object-pattern.html)

**Comment by vfabing** [comment]
Fixed ! Thanks mate 👍
